exec-once = systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP HYPRLAND_INSTANCE_SIGNATURE; systemctl --user start my-graphical-session.target

exec-once = hyprctl setcursor Adwaita 20
exec-once = hyprctl switchxkblayout all 0
exec-once = pgrep "tmux: server" && exec foot -a foot-tmux -- tmux attach || exec foot -a foot-tmux -- tmux

exec-shutdown = systemctl --user stop my-graphical-session.target
exec-shutdown = systemctl --user unset-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP HYPRLAND_INSTANCE_SIGNATURE

