exec-once = systemctl --user start my-graphical-session.target
exec-shutdown = systemctl --user stop my-graphical-session.target

exec-once = hyprctl setcursor Adwaita 20
exec-once = hyprctl switchxkblayout all 0
exec-once = pgrep "tmux: server" && exec foot -a foot-tmux -- tmux attach || exec foot -a foot-tmux -- tmux

