animations {
    enabled = false
}

background {
    path = screenshot
    blur_passes = 1
}

label {
    position = 0, 25%
    text = $TIME
    font_family = JetBrainsMono Nerd Font
    font_size = 48
}

input-field {
    size = 20%, 5%
    rounding = 0
    fade_on_empty = false

    font_family = JetBrainsMono Nerd Font
    dots_text_format = *
    dots_center = false
}

