L+ %h/.config/discord - - - - %h/.local/share/discord

d %h/.cache/discord/Cache
L+ %h/.local/share/discord/Cache - - - - %h/.cache/discord/Cache

d %h/.cache/discord/Code\x20Cache
L+ %h/.local/share/discord/Code\x20Cache - - - - %h/.cache/discord/Code\x20Cache

d %h/.cache/discord/DawnGraphiteCache
L+ %h/.local/share/discord/DawnGraphiteCache - - - - %h/.cache/discord/DawnGraphiteCache

d %h/.cache/discord/DawnWebGPUCache
L+ %h/.local/share/discord/DawnWebGPUCache - - - - %h/.cache/discord/DawnWebGPUCache

d %h/.cache/discord/GPUCache
L+ %h/.local/share/discord/GPUCache - - - - %h/.cache/discord/GPUCache

d %h/.cache/discord/discord_asset_cache
L+ %h/.local/share/discord/discord_asset_cache - - - - %h/.cache/discord/discord_asset_cache

