# Breaks gradle.
# Possibly related: https://github.com/gradle/gradle/pull/38153

#d %h/.cache/gradle/caches
#L+ %h/.local/share/gradle/caches - - - - %h/.cache/gradle/caches

#d %h/.cache/gradle/tmp
#L+ %h/.local/share/gradle/.tmp - - - - %h/.cache/gradle/tmp

