d %h/.cache/TelegramDesktop/audio_cache

L+ %h/.local/share/TelegramDesktop/tdata/audio_cache - - - - %h/.cache/TelegramDesktop/audio_cache

d %h/.cache/TelegramDesktop/user_data/cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data/cache - - - - %h/.cache/TelegramDesktop/user_data/cache
d %h/.cache/TelegramDesktop/user_data/media_cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data/media_cache - - - - %h/.cache/TelegramDesktop/user_data/media_cache

d %h/.cache/TelegramDesktop/user_data\x232/cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x232/cache - - - - %h/.cache/TelegramDesktop/user_data\x232/cache
d %h/.cache/TelegramDesktop/user_data\x232/media_cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x232/media_cache - - - - %h/.cache/TelegramDesktop/user_data\x232/media_cache

d %h/.cache/TelegramDesktop/user_data\x233/cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x233/cache - - - - %h/.cache/TelegramDesktop/user_data\x233/cache
d %h/.cache/TelegramDesktop/user_data\x233/media_cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x233/media_cache - - - - %h/.cache/TelegramDesktop/user_data\x233/media_cache

d %h/.cache/TelegramDesktop/user_data\x234/cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x234/cache - - - - %h/.cache/TelegramDesktop/user_data\x234/cache
d %h/.cache/TelegramDesktop/user_data\x234/media_cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x234/media_cache - - - - %h/.cache/TelegramDesktop/user_data\x234/media_cache

d %h/.cache/TelegramDesktop/user_data\x235/cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x235/cache - - - - %h/.cache/TelegramDesktop/user_data\x235/cache
d %h/.cache/TelegramDesktop/user_data\x235/media_cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x235/media_cache - - - - %h/.cache/TelegramDesktop/user_data\x235/media_cache

d %h/.cache/TelegramDesktop/user_data\x236/cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x236/cache - - - - %h/.cache/TelegramDesktop/user_data\x236/cache
d %h/.cache/TelegramDesktop/user_data\x236/media_cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x236/media_cache - - - - %h/.cache/TelegramDesktop/user_data\x236/media_cache

d %h/.cache/TelegramDesktop/user_data\x237/cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x237/cache - - - - %h/.cache/TelegramDesktop/user_data\x237/cache
d %h/.cache/TelegramDesktop/user_data\x237/media_cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x237/media_cache - - - - %h/.cache/TelegramDesktop/user_data\x237/media_cache

d %h/.cache/TelegramDesktop/user_data\x238/cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x238/cache - - - - %h/.cache/TelegramDesktop/user_data\x238/cache
d %h/.cache/TelegramDesktop/user_data\x238/media_cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x238/media_cache - - - - %h/.cache/TelegramDesktop/user_data\x238/media_cache

d %h/.cache/TelegramDesktop/user_data\x239/cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x239/cache - - - - %h/.cache/TelegramDesktop/user_data\x239/cache
d %h/.cache/TelegramDesktop/user_data\x239/media_cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x239/media_cache - - - - %h/.cache/TelegramDesktop/user_data\x239/media_cache

d %h/.cache/TelegramDesktop/user_data\x2310/cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x2310/cache - - - - %h/.cache/TelegramDesktop/user_data\x2310/cache
d %h/.cache/TelegramDesktop/user_data\x2310/media_cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x2310/media_cache - - - - %h/.cache/TelegramDesktop/user_data\x2310/media_cache

d %h/.cache/TelegramDesktop/user_data\x2310/cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x2310/cache - - - - %h/.cache/TelegramDesktop/user_data\x2310/cache
d %h/.cache/TelegramDesktop/user_data\x2310/media_cache
L+ %h/.local/share/TelegramDesktop/tdata/user_data\x2310/media_cache - - - - %h/.cache/TelegramDesktop/user_data\x2310/media_cache

