d %h/.cache/Vencord/ExtensionCache
L+ %h/.config/Vencord/ExtensionCache - - - - %h/.cache/Vencord/ExtensionCache

d %h/.local/share/Vencord/dist
L+ %h/.config/Vencord/dist - - - - %h/.local/share/Vencord/dist

