# XDG user dirs
XDG_CONFIG_HOME=${HOME}/.config
XDG_DATA_HOME=${HOME}/.local/share
XDG_STATE_HOME=${HOME}/.local/state
XDG_CACHE_HOME=${HOME}/.cache

INPUTRC=${XDG_CONFIG_HOME}/inputrc
W3M_DIR=${XDG_CONFIG_HOME}/w3m
_JAVA_OPTIONS=-Djava.util.prefs.userRoot=${XDG_CONFIG_HOME}/java

WINEPREFIX=${XDG_DATA_HOME}/wineprefix
GNUPGHOME=${XDG_DATA_HOME}/gnupg
ANDROID_USER_HOME=${XDG_DATA_HOME}/android
GRADLE_USER_HOME=${XDG_DATA_HOME}/gradle

__GL_SHADER_DISK_CACHE_PATH=${XDG_CACHE_HOME}/nv
CUDA_CACHE_PATH=${XDG_CACHE_HOME}/nv/
npm_config_cache=${XDG_CACHE_HOME}/npm
PNPM_HOME=${XDG_CACHE_HOME}/pnpm
CARGO_HOME=${XDG_CACHE_HOME}/cargo
GOPATH=${XDG_CACHE_HOME}/go
PYTHON_HISTORY=${XDG_CACHE_HOME}/python_history
TEXMFVAR=${XDG_CACHE_HOME}/texlive/texmf-var
RLWRAP_HOME=${XDG_CACHE_HOME}/rlwrap

CMAKE_EXPORT_COMPILE_COMMANDS=1

# see .zprofile
PARSED_CONFIG_ENVIRONMENT_D=1

