# Disable GTK accessibility bus
GTK_A11Y=none
NO_AT_BRIDGE=1

# Firefox settings
# hwaccel refuses to work without this
MOZ_DISABLE_RDD_SANDBOX=1
MOZ_DRM_DEVICE=/dev/dri/by-name/amdgpu-render

# Wayland in QT apps
QT_QPA_PLATFORM=wayland
QT_QPA_PLATFORMTHEME=xdgdesktopportal
QT_WAYLAND_DISABLE_WINDOWDECORATION=1

# Nvidia, FUCK YOU
VDPAU_DRIVER=radeonsi
LIBVA_DRIVER_NAME=radeonsi

